<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>29803dc5-d1ed-4785-a383-d29605883dde</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Budget.Application\Budget.Application.csproj" />
    <ProjectReference Include="..\Budget.Application.Contrats\Budget.Application.Contrats.csproj" />
    <ProjectReference Include="..\Budget.Application.Dtos\Budget.Application.Dtos.csproj" />
    <ProjectReference Include="..\Budget.Infrastructure.Persistence\Budget.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\Budget.Infrastructure.Exceptions\Budget.Infrastructure.Exceptions.csproj" />
    <ProjectReference Include="..\Budget.Shared\Budget.Shared.csproj" />
    <ProjectReference Include="..\Budget.Application.Adapters\Budget.Application.Adapters.csproj" />
  </ItemGroup>

</Project>
